#Ensure working directory contains HEP[year]Survey123 folders with Raw Downlaods subfolders containing series of Survey123 data backups

library(tidyverse)

#manually specify year below
zyear <- "2023"
#List files within directory for S123 downloads for zyear, Filter to only files with correct start to name structure
S123Files <- as.data.frame(list.files(paste("./HEP", zyear, "Survey123/RawDownloads", sep = ""), full.names = TRUE)) %>%
  setNames(c("Filename")) %>%
  filter(grepl(paste("HEP_", zyear, "_", sep=""), Filename))
S123DownloadFilesVector <- as.vector(S123DownloadFiles$Filename)
#Read in each .csv
ListDownloadsRaw <- lapply(S123DownloadFilesVector, function(zfilename){
  read.csv(zfilename) %>%
    mutate(DownloadVersion = substring(zfilename, 42, 44))
})
#Bind rows, filter to unique records based on record ID generated by esri, review notes
dfDownloadsUnique <- bind_rows(ListDownloadsRaw) %>%
  distinct(ï..ObjectID, reviewnotes, .keep_all = T)
#Export condensed .csv
write.csv(dfDownloadsUnique, file = paste("./HEP", zyear, "Survey123/", zyear, "RecordsCombined.csv", sep = ""))
