---
title: "Heron and Egret Project Season Summary Form"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)


```


```{r}

library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(rhandsontable)
library(flextable)
library(officer)
library(here)
library(knitr)
source(here("code/append_species_not_nesting.r"))
options(scipen = 999)
lead.col.width = c(0.5, 0.6, 0.75)
date.col.width = 0.6

```

```{r}
# step 1: input the year you are working with and read in the wrangled Survey123 data
zyear = 2020
wrangled_s123 <- readRDS(here(paste("data/wrangled/wrangled_s123", zyear, sep = "_")))



# step 2: check which season summary sheets have already been created
# readRDS(here(paste("season_summary_forms/sheet_creation_logs/sheet_creation_log_", zyear, sep = ""))) %>% view()



# step 3: input the colony code and species you want to generate a season summary sheet for

zcode = "599"
zspp = "GREG"


# step 4: check if the species nested in the selected colony and year; if not, do not need to create season summary sheet.
# wrangled_s123$nests %>% filter(species == zspp, code == zcode) %>% summarize(max(total.nests))


# if this value is > 0, can click knit above and the season summary sheet will be generated
# if this value = 0, append the didn't nest list:
if(wrangled_s123$nests %>% filter(species == zspp, code == zcode) %>% summarize(max(total.nests)) == 0) {
  knit_exit()
}

```

```{r}

# create a log of when this season summary sheet was created
if(file.exists(here(paste("season_summary_forms/sheet_creation_logs/sheet_creation_log_", zyear, sep = "")))) {
readRDS(here(paste("season_summary_forms/sheet_creation_logs/sheet_creation_log_", zyear, sep = ""))) %>% 
  rbind(data.frame(year = zyear,
                   code = zcode,
                   species = zspp,
                   date.sheet.created = Sys.time())) %>% 
  distinct(year, code, species, .keep_all = TRUE) %>% 
  saveRDS(here(paste("season_summary_forms/sheet_creation_logs/sheet_creation_log_", zyear, sep = "")))
} else {
  data.frame(year = zyear,
             code = zcode,
             species = zspp,
             date.sheet.created = Sys.time()) %>% 
  saveRDS(here(paste("season_summary_forms/sheet_creation_logs/sheet_creation_log_", zyear, sep = "")))
}

```

```{r}
# make a blank table to record screener initials

screeners <- data.frame(year = zyear,
                        code = zcode,
                        species = zspp,
                        screener.1 = "not screened",
                        screener.2 = "not screened",
                        screening.notes = "")

```
\fontsize{12}{22}
Screener initials:
```{r ft.align="left"}
flextable(screeners) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 4:5, width = 1) %>% 
  width(j = 6, width = 3)
```


<br>
```{r}
# make colony/effort summary box

colony <- wrangled_s123$sites %>% 
  filter(code == zcode) 


seas_summary_observers <- wrangled_s123$observers %>% 
  filter(code == zcode) %>% 
  filter(name != "other") %>% 
  mutate(name = ifelse(grepl("Recording", role), paste(name, "*", sep = ""), name)) %>% 
  distinct(code, name) %>% 
  group_by(code) %>% 
  summarise(observers = paste(name, collapse = "; ")) %>% 
  ungroup() %>% 
  mutate(observers = gsub("([[:lower:]])([[:upper:]][[:lower:]])", "\\1 \\2", observers)) # add space between first and last names
  
dates <- wrangled_s123$dates %>% 
  filter(code == zcode)

  
dates <- wrangled_s123$dates %>% 
  filter(code == zcode)

top_table <- data.frame(year = zyear,
                        code = colony$code,
                        species = zspp,
                        colony = colony$site.name,
                        observers = seas_summary_observers$observers,
                        total.days = nrow(distinct(dates, date)),
                        total.surveys = nrow(dates),
                        total.hours = round(as.numeric(sum(dates$total.minutes)),2))

  

```

```{r}
flextable(top_table) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width)

```
 *indicates recording observer

<br>

```{r}


# total nests  
total.nests <- wrangled_s123$nests %>% 
  filter(code == zcode, species == zspp) %>% 
  select(species, date, multiple.survey.num, total.nests) %>%  
  arrange(date) %>% 
  mutate(date = as.character(date),
         date = gsub(paste(zyear, "-", sep = ""), "", date),
         date = ifelse(multiple.survey.num > 1, paste(date, multiple.survey.num, sep = "."), date)) %>% 
  select(-multiple.survey.num) %>% 
  pivot_wider(values_from = total.nests, names_from = date) %>% 
  mutate(variable = "total.nests") %>% 
  select(variable, everything())

peak_active <- wrangled_s123$nests %>% 
  filter(code == zcode, species == zspp) %>% 
  select(species, date, multiple.survey.num, peak.active)  %>% 
  arrange(date) %>% 
  mutate(date = as.character(date),
         date = gsub(paste(zyear, "-", sep = ""), "", date),
         date = ifelse(multiple.survey.num > 1, paste(date, multiple.survey.num, sep = "."), date)) %>% 
  select(-multiple.survey.num) %>% 
  pivot_wider(values_from = peak.active, names_from = date) %>% 
  mutate(variable = "peak.active") %>% 
  select(variable, everything())
  





nest_totals_df <- rbind(total.nests, peak_active) %>% 
  mutate(year = zyear,
         code = zcode) %>% 
  select(year, code, species, everything())
    
```

```{r}

date_table_splitter <- function(ztable, num_dates_per_split = 6) {

num.splits <- ceiling((ncol(ztable) - 4) / num_dates_per_split)

seq.splits <- seq(1, num.splits)

col.splits <- 4 + (num_dates_per_split * seq.splits)

lead.cols <- c(1:4)

ztable1_cols <- c(lead.cols, 5:col.splits[1])
# define sub-table 1 columns

  if(ncol(ztable) <= col.splits[1]){
ztable1_cols <- c(1:ncol(ztable))
  }  
  if(ncol(ztable) > col.splits[1]){
ztable1_cols <- c(1:col.splits[1])
}

# define sub-table 2 columns
if(length(col.splits) > 1){
if(ncol(ztable) > col.splits[1]) {
  if(ncol(ztable) <= col.splits[2]){
ztable2_cols <- c(lead.cols, (col.splits[1]+1):ncol(ztable))
  }  
  if(ncol(ztable) > col.splits[2]){
ztable2_cols <- c(lead.cols, (col.splits[1]+1):col.splits[2])
}
}
}
# define sub-table 3 columns
if(length(col.splits) > 2) {
if(ncol(ztable) > col.splits[2]) {
  if(ncol(ztable) <= col.splits[3]){
ztable3_cols <- c(lead.cols, (col.splits[2]+1):ncol(ztable))
  }  
  if(ncol(ztable) > col.splits[3]){
ztable3_cols <- c(lead.cols, (col.splits[2]+1):col.splits[3])
}
}
}
# define sub-table 4 columns
if(length(col.splits) > 3) {
if(ncol(ztable) > col.splits[3]) {
  if(ncol(ztable) <= col.splits[4]){
ztable4_cols <- c(lead.cols, (col.splits[3]+1):ncol(ztable))
  }  
  if(ncol(ztable) > col.splits[4]){
ztable4_cols <- c(lead.cols, (col.splits[3]+1):col.splits[4])
}
}
}
# define sub-table 5 columns
if(length(col.splits) > 4) {
if(ncol(ztable) > col.splits[4]) {
  if(ncol(ztable) <= col.splits[5]){
ztable5_cols <- c(lead.cols, (col.splits[4]+1):ncol(ztable))
  }  
  if(ncol(ztable) > col.splits[5]){
ztable5_cols <- c(lead.cols, (col.splits[4]+1):col.splits[5])
}
} 
}

#--- make sub table 1
sub_table1 <- flextable(ztable[,ztable1_cols]) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 5:length(ztable1_cols), width = date.col.width)

#--- make sub table 2
if(exists("ztable2_cols")) {
  
sub_table2 <- flextable(ztable[ztable2_cols]) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 5:length(ztable2_cols), width = date.col.width)
} else {
  sub_table2 <- NULL
}
#--- make sub table 3
if(exists("ztable3_cols")) {
  
sub_table3 <- flextable(ztable[ztable3_cols]) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 5:length(ztable3_cols), width = date.col.width)
} else {
  sub_table3 <- NULL
}
#--- make sub table 4
if(exists("ztable4_cols")) {
  
sub_table4 <- flextable(ztable[ztable4_cols]) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 5:length(ztable4_cols), width = date.col.width)
} else {
  sub_table4 <- NULL
}
#--- make sub table 5
if(exists("ztable5_cols")) {
  
sub_table5 <- flextable(ztable[ztable5_cols]) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5) %>% 
  width(j = 1:3, width = lead.col.width) %>% 
  width(j = 5:length(ztable5_cols), width = date.col.width)
} else {
  sub_table5 <- NULL
}

out_sub_tables <- list(sub_table1 = sub_table1,
                       sub_table2 = sub_table2,
                       sub_table3 = sub_table3,
                       sub_table4 = sub_table4,
                       sub_table5 = sub_table5)
return(out_sub_tables)
}

```
<br>
Total nests
```{r}
nest_totals <- date_table_splitter(nest_totals_df)
```

```{r}
nest_totals$sub_table1
```
<br>
```{r}
nest_totals$sub_table2
```
<br>
```{r}
nest_totals$sub_table3
```
<br>
```{r}
nest_totals$sub_table4
```
<br>
```{r}
nest_totals$sub_table5
```



<br>
Number of nests at each stage
```{r}

if(zspp %in% c("GREG", "GBHE")) {
nest_stages_df <- wrangled_s123$stages %>% 
  filter(code == zcode, species == zspp) %>% 
  mutate(stage = paste("stage", stage, sep = ".")) %>% 
  arrange(date) %>% 
  mutate(date = as.character(date),
         date = gsub(paste(zyear, "-", sep = ""), "", date),
         date = ifelse(multiple.survey.num > 1, paste(date, multiple.survey.num, sep = "."), date),
         num.nests = as.character(num.nests)) %>% 
  select(-multiple.survey.num) %>% 
  pivot_wider(id_cols = stage, names_from = date, values_from = num.nests) %>% 
  mutate(year = zyear,
         code = zcode,
         species = zspp) %>% 
  rename(variable = stage) %>% 
  select(year, code, species, everything())

rop <- dates %>% 
  select(date, multiple.survey.num, which.rop) %>% 
  arrange(date) %>% 
  mutate(date = as.character(date),
         date = gsub(paste(zyear, "-", sep = ""), "", date),
         date = ifelse(multiple.survey.num > 1, paste(date, multiple.survey.num, sep = "."), date)) %>% 
  select(-multiple.survey.num) %>% 
  mutate(which.rop = ifelse(is.na(which.rop), "other", which.rop)) %>% 
  pivot_wider(values_from = which.rop, names_from = date) %>% 
  mutate(variable = "rop",
         species = zspp,
         year = zyear,
         code = zcode) %>% 
  select(variable, species, everything())

nest_stages_df <- full_join(nest_stages_df, rop)

}
```

```{r}
if(!zspp %in% c("GREG", "GBHE")) {
print(paste("No nest stage data for", zspp))
}
```

```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages <- date_table_splitter(nest_stages_df)
}
```
<br>

```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages$sub_table1
}
```
<br>
```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages$sub_table2
}
```
<br>
```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages$sub_table3
}
```
<br>
```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages$sub_table4
}
```
<br>
```{r}
if(zspp %in% c("GREG", "GBHE")) {
nest_stages$sub_table5
}
```
<br>
<br>

```{r}
# stage 4 brood sizes
first_stage5_date <- wrangled_s123$stages %>% 
  filter(code == zcode, species == zspp) %>%
  filter(stage == 5, num.nests > 0) %>% 
  filter(date == min(date)) %>% 
  select(code, species, date)
if(nrow(first_stage5_date) == 0) {
  first_stage5_date = data.frame(code = zcode,
                                 species = zspp,
                                 date = NA)
}

brood_sizes <- wrangled_s123$brood.sizes %>% 
  filter(code == zcode, species == zspp) %>% 
  group_by(date) %>% 
  mutate(max.num.nest = max(num.nests)) %>% 
  ungroup() %>% 
  filter(max.num.nest > 0) %>% 
  mutate(stage5.nests = ifelse(date >= first_stage5_date$date, TRUE, FALSE)) %>% 
  group_by(stage5.nests) %>% 
  mutate(temp.max.date = max(date),
         stg4.date = ifelse(stage5.nests == FALSE & date == temp.max.date, TRUE, FALSE)) %>% 
  select(-max.num.nest, -temp.max.date)  




if(zspp %in% c("GREG", "GBHE")) {
  
if(nrow(brood_sizes) > 0) {
brood_sizes_wide <- brood_sizes %>% 
  mutate(brd = paste("brd.", brd, sep = ""),
         year = zyear) %>% 
  #mutate(stg4.date = ifelse(date == max(date), TRUE, FALSE)) %>% 
  mutate(date = as.character(date),
         date = ifelse(multiple.survey.num > 1, paste(date, multiple.survey.num, sep = "."), date)) %>% 
  select(-multiple.survey.num) %>% 
  pivot_wider(values_from = num.nests, names_from = brd) %>% 
  select(year, code, species, date, everything()) %>% 
  arrange(date)
} else {
  brood_sizes_wide <- data.frame(year = zyear,
                                 code = zcode,
                                 species = zspp,
                                 brd.date = NA,
                                 brd.1 = NA,
                                 brd.2 = NA,
                                 brd.3 = NA,
                                 brd.4 = NA,
                                 brd.5 = NA)
}
}
```
<br>
Number of Stage 4 nests
```{r}
if(!zspp %in% c("GREG", "GBHE")) {
print(paste("No stage 4 brood sizes for", zspp))
}
```

```{r}
if(zspp %in% c("GREG", "GBHE")) {
flextable(brood_sizes_wide) %>% 
  autofit() %>% 
    width(c(1:2, 7:11), width = 0.5)
}
```
note: only dates with at least 1 stage 4 nest are shown 

```{r}
# disturbance
disturbance <- wrangled_s123$disturbance %>% 
  filter(code == zcode) %>% 
  mutate(year = year(as.Date(date))) %>% 
  select(year, code, date, observed.inferred = obs.inf, description = details, type = source, result)

```
<br>
Disturbance to colony
```{r}
flextable(disturbance) %>% 
  autofit() %>% 
  fit_to_width(max_width = 8.5)
```


```{r}
# predators
predators <- wrangled_s123$predators %>% 
  filter(code == zcode) %>% 
  select(code, predator.species, species.nesting) %>% 
  separate(predator.species, into = paste("pred.sp", seq(1:6))) %>% 
  separate(species.nesting, into = paste("pred.sp.nest", seq(1:6))) 

predators_longer <- predators %>% 
  pivot_longer(cols = contains("pred"), values_to = "predator.species") %>% 
  filter(!is.na(predator.species), predator.species != "") %>% 
  mutate(pres.nest = ifelse(grepl("nest", name), "nesting", "present")) %>% 
  distinct(code, predator.species, pres.nest)

predators_rewide <- predators_longer %>% 
  mutate(yup = 1) %>% 
  pivot_wider(id_cols = c(predator.species, code), names_from = pres.nest, values_from = yup) %>% 
  mutate(year = zyear) %>% 
  select(year, code, everything())

```
<br> 
Nest predatory species
```{r}
flextable(predators_rewide) %>% 
  autofit()

```

<br>
```{r}

notes <- wrangled_s123$notes %>% 
  filter(code == zcode) %>% 
  select(-multiple.survey.num) %>% 
  pivot_longer(cols = contains("notes"), names_to = "note.type", values_to = "notes") %>% 
  filter(!is.na(notes), notes != "", notes != "na") %>% 
  mutate(note.type = gsub(".notes", "", note.type))


```

<br> 
Notes
```{r}
flextable(notes) %>% 
  width(1, width = .5) %>% 
  width(2:3, width = 1) %>% 
  width(4, width = 4) %>% 
  valign(valign = "top")

```

<br>
Season Summary stat sheet - DO NOT EDIT

```{r}
seas_summary_stat_sheet <- data.frame(num_total_nest_tables = length(nest_totals[-which(sapply(nest_totals, is.null))]),
                                      num_nest_stage_tables = ifelse(exists("nest_stages"), 
                                                                            length(nest_stages[-which(sapply(nest_stages, is.null))]),
                                                                            0))


```

```{r}
flextable(seas_summary_stat_sheet) %>% 
  autofit()

```

